import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ToasterComponent from '@/components/Global/ToasterComponent';
import AppProviders from '@/Provider/AppProviders';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Meh Instrument Store',
  description: 'Generated by Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-slate-200  antialiased`}
        >
          <ToasterComponent />
          {children}
        </body>
      </AppProviders>
    </html>
  );
}
